stream.rules = [
  {
    matches = [
      {
        node.name = "~.*[Cc]hrome.*"
      }
    ]
    actions = {
      update-props = {
        application.name = "Google Chrome"
        application.id = "google-chrome"
        state.restore-target = false
      }
    }
  }
  {
    matches = [
      {
        node.name = "~.*[Ff]irefox.*"
      }
    ]
    actions = {
      update-props = {
        application.name = "Firefox"
        application.id = "firefox"
        target.object = "SilentRecording"
      }
    }
  }
]
