stream.rules = [
  {
    matches = [
      {
        node.name = "~.*[Ff]irefox.*"
      }
    ]
    actions = {
      update-props = {
        target.object = "SilentRecording"
        state.restore-target = false
      }
    }
  }
]
