[global]
   workgroup = WORKGROUP
   server string = DietPi NAS Server
   security = user
   map to guest = Bad User
   dns proxy = no
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   usershare allow guests = yes
   
   # Performance Tweaks
   min receivefile size = 16384
   use sendfile = yes
   aio read size = 16384
   aio write size = 16384
   socket options = TCP_NODELAY IPTOS_LOWDELAY

[dietpi]
   path = /home/dietpi
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[dietpi-home]
   path = /home/dietpi
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[books]
   path = /mnt/books
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[media1]
   path = /mnt/media1
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[media2]
   path = /mnt/media2
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[tvShows]
   path = /mnt/tvShows
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[scratch]
   path = /mnt/scratch
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = dietpi pom root

[root]
   path = /
   read only = no
   browsable = yes
   writable = yes
   guest ok = no
   create mask = 0775
   directory mask = 0775
   valid users = root dietpi pom
