---
- name: Ensure Flathub repository is enabled
  ansible.builtin.command:
    cmd: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true
  changed_when: false

- name: Install curated Flatpak applications
  ansible.builtin.command:
    cmd: "flatpak install -y --noninteractive flathub {{ item }}"
  loop: "{{ flatpak_apps }}"
  become: true
  changed_when: false
  ignore_errors: true
