context.objects = [
    { factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "silent_sink"
            node.description = "Silent_Sink"
            media.class      = "Audio/Sink"
            audio.position   = "FL,FR"
        }
    }
]
