context.objects = [
    { factory = adapter
      args = {
          factory.name     = support.null-audio-sink
          node.name        = "SilentRecording"
          node.description = "Silent_Recording"
          media.class      = "Audio/Sink"
          audio.position   = "FL,FR"
      }
    }
]
